# Generated by Django 5.0 on 2024-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mechanics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="mechanics"),
                ),
                ("name", models.CharField(max_length=255)),
                ("proffesion", models.CharField(max_length=255)),
                ("years", models.CharField(max_length=255)),
                ("mobile", models.TextField()),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, null=True)),
                ("bookDate", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("mobile", models.TextField()),
                ("email", models.TextField()),
            ],
        ),
    ]
