# Generated by Django 5.0 on 2024-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanics",
            name="years",
        ),
        migrations.AlterField(
            model_name="mechanics",
            name="mobile",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="email",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="mobile",
            field=models.CharField(max_length=10),
        ),
    ]
