# Generated by Django 5.0 on 2024-03-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mechanics",
            "0003_alter_mechanics_options_alter_reservations_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservations",
            name="bookTime",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reservations",
            name="mechanic_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mechanics.mechanics",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservations",
            name="bookDate",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
